# Generated by Django 4.2.7 on 2023-11-26 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='End_Date',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='Start_Date',
            field=models.TextField(),
        ),
    ]
